#!/usr/bin/env bash
set -euo pipefail

# Non-test usage: do not commit live keys. Export these before running:
#   export STACKFLOW_NODE_DISPUTE_SIGNER_KEY=...
# Optional local-key mode:
#   export STACKFLOW_NODE_COUNTERPARTY_KEY=...
#   export STACKFLOW_NODE_COUNTERPARTY_PRINCIPAL=ST...

: "${STACKFLOW_NODE_DISPUTE_SIGNER_KEY:?STACKFLOW_NODE_DISPUTE_SIGNER_KEY is required}"

STACKFLOW_NODE_HOST="${STACKFLOW_NODE_HOST:-127.0.0.1}" \
STACKFLOW_NODE_PORT="${STACKFLOW_NODE_PORT:-8787}" \
STACKS_NETWORK="${STACKS_NETWORK:-devnet}" \
STACKS_API_URL="${STACKS_API_URL:-http://localhost:3999}" \
STACKFLOW_CONTRACTS="${STACKFLOW_CONTRACTS:-ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.stackflow}" \
STACKFLOW_NODE_SIGNATURE_VERIFIER_MODE="${STACKFLOW_NODE_SIGNATURE_VERIFIER_MODE:-readonly}" \
STACKFLOW_NODE_DISPUTE_EXECUTOR_MODE="${STACKFLOW_NODE_DISPUTE_EXECUTOR_MODE:-auto}" \
STACKFLOW_NODE_COUNTERPARTY_SIGNER_MODE="${STACKFLOW_NODE_COUNTERPARTY_SIGNER_MODE:-kms}" \
npm run stackflow-node
